search/urls.py
from django.urls import path, include
from search.views import searchView


app_name = "search"
urlpatterns = [
    path('', searchView, name='search'),
]

site_news/urls.py
from django.urls import path
from .views import *

app_name = "news"
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('actualites/', ActualitesView.as_view(), name='actualites'),
    path('article/<int:id>/<slug:slug>/<str:tag>/', ArticleDetailView.as_view(), name='article'),
    path('videos/', VideoView.as_view(), name='videos-list'),
    path('video/<int:id>/<slug:slug>/<str:tag>/', VideoDetailView.as_view(), name="single-video"),
    path('categorie/<int:pk>/<str:description>/', CategoryView.as_view(), name="category"),
    path('evenements/', EventView.as_view(), name='events'),
]

search/models.py
from django.db import models

# Create your models here.

site_news/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils import timezone, html
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField

from site_news.utils import (uploadToArticle,
                             uploadToPublicite,
                             uploadToEvent)

User = get_user_model()


def get_youtube_embed_url(url_link=None):
    if url_link:
        embed_url = url_link.replace('watch?v=', 'embed/')
        return embed_url
    pass


# User = get_user_model()
class Country(models.Model):
    country = CountryField(blank_label=_('Choisir Pays'), default='CI', unique=True)

    # country_name = models.CharField(_("Pays"), max_length=100, default="Côte d'Ivoire", null=True, blank=True)
    # country_code = models.CharField(_("Code"), max_length=50, null=True, blank=True)

    def __str__(self):
        return str(self.country.name)

    class Meta:
        verbose_name = _('Pays')
        verbose_name_plural = _("Pays")


class Category(models.Model):
    description = models.CharField(
        unique=True,
        verbose_name=_("Libellé"),
        max_length=20,
        null=False,
        blank=False
    )

    class Meta:
        verbose_name = _('Catégorie')
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.description

    def get_absolute_url(self, *args, **kwargs):
        return reverse("news:category", kwargs={"pk": self.pk, 'description': self.description})


class MediaType(models.Model):
    IMAGE = 'image'
    VIDEO = 'video'
    AUDIO = "audio"
    PDF = "pdf"
    XDOC = "xdoc"
    MEDIA_TYPE = [
        (IMAGE, "IMAGE"),
        (VIDEO, 'VIDEO'),
        (AUDIO, 'AUDIO'),
        (PDF, 'PDF'),
        (XDOC, 'AUTRE DOCUMENT'),
    ]

    media_type = models.CharField(choices=MEDIA_TYPE,
                                  max_length=5,
                                  default=IMAGE,
                                  unique=True)

    def __str__(self):
        return self.get_media_type_display()


class Article(models.Model):
    # country = models.ForeignKey(Country,
    #                             on_delete=models.CASCADE,
    #                             verbose_name=_("Pays"),
    #                             related_name="articles")
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE,
                                 verbose_name=_("Catégorie"),
                                 related_name="articles")
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               verbose_name="Auteur",
                               related_name="articles")
    title = models.CharField(_("Titre de l'article"),
                             max_length=250,
                             unique=True, )
    content = RichTextUploadingField(verbose_name="Contenu",
                                     default="Contenu article")
    tag = models.CharField(_("Ajouter un Tag"),
                           max_length=50,
                           default="article",
                           help_text="Ex: video, article, event")
    created = models.DateTimeField(
        verbose_name=_("Date de création"),
        auto_now_add=True,
        auto_now=False
    )
    published_date = models.DateTimeField(
        verbose_name=_("Date de publication"),
        default=timezone.now,
    )
    updated = models.DateTimeField(
        auto_now=True,
        auto_now_add=False
    )
    updated_by = models.ForeignKey(User,
                                   on_delete=models.SET_NULL,
                                   verbose_name="Modifié par",
                                   null=True,
                                   blank=True,
                                   )
    slug = models.SlugField(max_length=255)
    view = models.IntegerField(_("Vue"), default=0)

    class Meta:
        ordering = ['-published_date']

    def __str__(self):
        return self.title

    def save(self, **kwargs):
        self.slug = slugify(self.title)
        super(Article, self).save()

    def get_absolute_url(self, **kwargs):
        if self.tag == "article":
            return reverse("news:article",
                           kwargs={
                               "slug": str(self.slug),
                               "id": str(self.pk),
                               "tag": self.tag
                           })
        elif self.tag == "video":
            return reverse("news:single-video",
                           kwargs={
                               "slug": str(self.slug),
                               "id": str(self.pk),
                               "tag": self.tag
                           })
        else:
            return reverse("news:events")

    def articleViewCounter(self):
        if self.get_absolute_url():
            self.view += 1
            super().save()

    def displayShortArticle(self):
        return html.strip_tags(self.content[:200])

    displayShortArticle.short_description = "Contenus"


class MediaElement(models.Model):
    article = models.ForeignKey(Article,
                                verbose_name=_("Conetnu"),
                                on_delete=models.CASCADE,
                                related_name="medias",
                                default=1)
    media_type = models.ForeignKey(MediaType,
                                   verbose_name=_("Type de media"),
                                   on_delete=models.CASCADE)
    title = models.CharField(_("Description"),
                             max_length=255,
                             unique=True
                             )
    source = models.ImageField(_("Source"),
                               upload_to=uploadToArticle,
                               height_field=None,
                               width_field=None,
                               max_length=255)
    url = models.URLField(_("Lien de la vidéo"),
                          max_length=200,
                          unique=True,
                          help_text="Insérer le lien de la vidéo à publier, " \
                                    "ex:'https://www.youtube.com/watch?v=yHge5herg5_s",
                          null=True,
                          blank=True, )

    def __str__(self):
        return self.title

    def save(self, **kwargs):
        self.url = get_youtube_embed_url(self.url)
        super(MediaElement, self).save(**kwargs)


class Event(models.Model):
    event_date = models.DateTimeField(_("Date de l'événement"),
                                      default=timezone.now,
                                      auto_now=False,
                                      auto_now_add=False)
    event_place = models.CharField(_("Lieu de l'événement"),
                                   max_length=150)
    event_title = models.CharField(_("Titre de l'événement"),
                                   max_length=250, db_index=True)
    media = models.ImageField(_("Image associée à l'événement"),
                              upload_to=uploadToEvent,
                              )
    description = RichTextUploadingField(
        help_text="A propos de l'événement",
        null=True,
        blank=True,
    )

    def __str__(self):
        return str(self.event_title)

    class Meta:
        verbose_name = _('Evénement')
        verbose_name_plural = _("Evénements")


class Publicite(models.Model):
    image = models.ImageField(
        upload_to=uploadToPublicite,
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name="publicite"
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    client = models.CharField(
        max_length=200
    )

    def __str__(self):
        return self.client

search/views.py
from django.shortcuts import render, redirect, reverse
from site_news.models import Category, Article
from django.db.models import Q


def searchView(request):
    try:
        q = request.GET.get('query')
    except:
        q = None
    if q:
        categories = Category.objects.all()
        queries = Article.objects.filter(
            Q(article__title__icontains=q) |
            Q(content__icontains=q) |
            Q(article__category__description__icontains=q)
        )
        template = "search/query_results.html"
        context = {
            "query": q, 
            "queries": queries,
            "categories": categories
            }
        return render(request, template, context)
    else:
        return redirect(reverse('news:home'))

site_news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import (Article, Category, Event, MediaElement, 
                    MediaType, Country,
                    )
from django.views.generic import TemplateView, ListView, DetailView
from django.utils import timezone as tz
from django.utils.html import format_html

from django.core.paginator import Paginator
from django.db.models import Q
from django.urls import reverse
import os
from marketing.forms import EmailingForm


def get_all_category(context):
    context['categories'] = Category.objects.all()
    return context

def get_videos_n_event(context):
    context['videos'] = Article.objects.filter(
        tag="video", published_date__lte=tz.now()
    ).order_by("-published_date")[:3]
    
    context['events'] = Event.objects.all()[:3]
    return context

class HomeView(TemplateView):
    model = Article
    template_name = 'site_news/index.html'
    context_object_name = "articles"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['articles'] = Article.objects.filter(
                published_date__lte=tz.now(),
                tag="article").order_by('-published_date')[1:4]

        context['last_video'] = Article.objects.filter(
                published_date__lte=tz.now(),
                tag='video').first()

        context['last_article'] = Article.objects.all().first()
        
        context['all_article'] = Article.objects.filter(
                published_date__lte=tz.now(),
            ).order_by('-published_date'
            ).distinct()[:6]

        context['more_view'] = Article.objects.filter(
                view__gte=5,
            )

        get_videos_n_event(context)
        return context


class ActualitesView(ListView):
    model = Article
    template_name = 'site_news/article_list.html'
    context_object_name = "actualites"
    ordering = '-published_date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['small_articles'] = Article.objects.filter(
            published_date__lte=tz.now(),
        ).order_by('-published_date')[1:3]

        context['actualites'] = Article.objects.all()[3:]
        context['last_article'] = Article.objects.filter(
            published_date__lte=tz.now(), tag="article"
        ).first()
        get_all_category(context)
        get_videos_n_event(context)
        return context


class ArticleDetailView(DetailView):
    model = Article
    template_name = "site_news/pages/details.html"
    context_object_name = "article"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article_category = self.object.category
        context['from_same_category'] = Article.objects.filter(
            Q(category__description = article_category)
            ).exclude(id=self.object.id)[:3]

        context['content'] = self.object.content
        get_videos_n_event(context)
        get_all_category(context)
        self.object.articleViewCounter()
        return context


class CategoryView(ListView):
    model = Category
    template_name = 'site_news/pages/category.html'
    data_context_name = 'categories'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_selected'] = get_object_or_404(Category, pk=self.kwargs['pk'], 
                                                        description=self.kwargs['description'])
        context['content'] = Article.objects.filter(
            category__description=context['category_selected']
            ).distinct()
        get_videos_n_event(context)
        get_all_category(context)
        return context


class VideoView(ListView):
    model = Article
    template_name = "site_news/videos.html"
    context_object_name = "videos"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['last_video'] = Article.objects.filter(
            tag='video', published_date__lte=tz.now()
        ).first()
        context['videos'] = Article.objects.filter(
            published_date__lte=tz.now(),
            tag="video"
            ).order_by('-published_date')[1:4]
        return context


class VideoDetailView(DetailView):
    model = Article
    template_name = "site_news/pages/videos_detail.html"
    context_object_name = "video"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article_category = self.object.category
        
        context['from_same_category'] = Article.objects.filter(
            Q(category__description = article_category, tag="video")
            ).exclude(id=self.object.id)[:3]
                
        get_videos_n_event(context)
        get_all_category(context)
        self.object.articleViewCounter()
        return context


class EventView(ListView):
    model = Event
    template_name = 'site_news/events.html'
    context_object_name = 'events'

    def get_queryset(self):
        return Event.objects.filter(
                            event_date__gte=tz.now()
                            ).order_by('event_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    

site_news/templates/site_news/pages/inc/search.html
<div class="container">
    <div class="row mb-5 mt-0 text-center">
        <div class="cell-md-6 cell-sm-8 offset-md-3 offset-sm-2">
            <form action="{% url 'search:search' %}" method="GET" class="cell-12">
                <input type="text" name="query" placeholder="Rechercher un article" data-role="input" data-search-button="true">
            </form>
        </div>
    </div>
</div>

site_news/templates/site_news/pages/inc/select_category.html
    <div data-role="panel"
        class="w-100 p-0"
        data-title-caption="<span class='text-upper'>Les Catégories</sapn>"
        data-title-icon="<span class='mif-leanpub'></span>"
        >
        <table class="table striped">
            {% for category in categories %}
                <tr>
                    <td class="label text-leader2">
                        <a href="{{ category.get_absolute_url }}">{{ category.description }}</a>
                    </td>
                    <td class="second-label">{{ category.articles.count }} </td>
                </tr>
            {% endfor %}
        </table>
    </div>

site_news/templates/site_news/pages/inc/video_n_event.html
{% load static %}
{% load humanize %}

    <div class="row ">
        <div class="cell-md-6 pr-2">
            <hr class="mt-15 border bd-dark border-top border-size-2">
            <div class="h3 text-upper text-bold muted p-0 m-0 fg-red">Events</div>                
            <div class="row mt-7">
                <div class="cell-md-12 cell-lg-12">
                    <div class="row">
                        <div class="cell-6">
                            <div class="img-container">
                                <img src="{% static 'img/logo.png' %}" alt="spectacle" class="">
                            </div>
                        </div>
                        <div class="cell-6">
                            <ul class="feed-list">
                                {% for event in events %}
                                    <li>
                                        <span class="label text-leader2">
                                            <span class="mif-chevron-right fg-red"></span>
                                            <a href="{% url 'news:events' %}#{{ event.id }}">
                                                {{ event }}
                                            </a><br>
                                            <span class="text-small ml-6 mt-3 fg-red">
                                                {{ event.event_place }} - {{ event.event_date | date }} {{ event.event_date | time }}
                                            </span><br>
                                            <span class="">{{ event.tags.description }}</span>
                                        </span>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="cell-md-6 pl-2">
            <hr class="mt-15 border bd-dark border-top border-size-2">
            <div class="h3 text-upper text-bold muted p-0 m-0 fg-red">Vidéos</div>                
            <div class="row mt-7">
                <div class="cell-md-12 cell-lg-12">
                    <div class="row">
                        <div class="cell-6">
                            <div class="img-container">
                                <img src="{% static 'img/logo.png' %}" alt="spectacle" class="">
                            </div>
                        </div>
                        <div class="cell-6">
                            <ul class="feed-list">
                                {% for video in videos %}
                                    <li>
                                        <span class="label text-leader2">
                                            <span class="mif-chevron-right fg-red"></span>
                                            <a href="{{ video.get_absolute_url }}">
                                                {{ video.title }}
                                            </a>
                                        </span>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>