search/urls.py
from django.urls import path, include
from search.views import searchView


app_name = "search"
urlpatterns = [
    path('', searchView, name='search'),
]

site_news/urls.py
from django.urls import path
from .views import *

app_name = "news"
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('actualites/', ActualitesView.as_view(), name='actualites'),
    path('article/<int:id>/<slug:slug>/<str:tag>/', ArticleDetailView.as_view(), name='article'),
    path('videos/', VideoView.as_view(), name='videos-list'),
    path('video/<int:id>/<slug:slug>/<str:tag>/', VideoDetailView.as_view(), name="single-video"),
    path('categorie/<int:pk>/<str:description>/', CategoryView.as_view(), name="category"),
    path('evenements/', EventView.as_view(), name='events'),
]

templates/inc/footer.html
{% load static %}

<div class="row">
    <div class="cell-md-3 text-center">
        <div class="h4 text-upper">Le griot d'Afrique</div>
        <ul class="inline-list reduce-1" id="social-menu">
            <li>
                <a href="https://www.facebook.com/SmartDevCI/"
                    ><span class="mif-facebook2 mif-2x"></span
                ></a>
            </li>
            <li>
                <a href="https://twitter.com/SmartDevCI"
                    ><span class="mif-twitter mif-2x"></span
                ></a>
            </li>
            <li>
                <a href="#"><span class="mif-youtube mif-2x"></span></a>
            </li>
            <li>
                <a href="https://github.com/smartdev/"
                    ><span class="mif-github mif-2x"></span
                ></a>
            </li>
        </ul> 
        <div class="second-label">
            2020 &copy; Fusion Production. Tous droits réservés
        </div>
    </div>
    <div class="cell-md-3 text-center fg-white">
        <div class="h4 text-upper">Liens utiles</div>
        <ul class="text-center" style="list-style-type: none; color: white ">
            <li><a href="{% url 'news:home' %}">Accueil</a></li>
            <li><a href="{% url 'news:actualites' %}">Actualités</a></li>
            <li><a href="{% url 'news:videos-list' %}">Videos</a></li>
            <li><a href="{% url 'news:events' %}">Evénements</a></li>
        </ul>
    </div>
    <div class="cell-md-3">
        {% include 'marketing/newsletter.html' %}
    </div>
    <div class="cell-md-3">
        <!-- <div class="h4 text-upper">Newsletters</div>
        <form action="">
            <input type="email" 
                data-role="input"
                data-search-button="true"
                data-search-button-icon="<span class='mif-paper-plane mif-2x'></span>"
                data-prepend="Email"
                placeholder="Entrer un email valid">
        </form> -->
        <div class="text-center second-label mt-5">
            <p class="text-leader">
                Conception & <br>développement 
            </p> 
            <a href="https://www.smartdevci.com" class="img-container mt-3">
                <img src="{% static 'img/logo-white.png' %}" alt="" class="image w-50">
            </a>
        </div>
    </div>
</div>

templates/inc/last_news.html
{% load static %}
{% load humanize %}

<!-- DERNIÈRE NOUVELLES -->       
<div class="row ">
    <div class="cell-md-12">
        <div class="h3 text-upper text-bold muted p-0 m-0 border">Dernières nouvelles</div>
    </div>
    <div class="cell-md-8 mt-5">
        <div class="row">
            {% for item in all_article %}
                <div class="cell-md-6 cell-lg-4">
                    <div class="card image-header p-0">
                        <div class="card-header w-100" 
                            {% for media in item.medias.all %}
                                {% if forloop.first  %}
                                    style="background-image: url({{ MEDIA_URL }}{{ media.source.url }})";
                                {% endif %}
                            {% endfor %}
                            >
                        </div>
                        <div class="card-content p-2">
                            <div class="badge inline bg-red fg-white">
                                {{ item.category }}
                            </div>
                            <hr>
                            <p class="muted fg-gray my-1">
{#                                <span class="mif-user mr-2"></span>#}
{#                                <strong class="fg-red">#}
{#                                    <em>{{ item.author | capfirst | default_if_none:'Ben Saiba' }}</em>#}
{#                                </strong>#}
                                <span class="mif-alarm mr-2"></span>
                                <em>{{ item.created | naturaltime }}</em>
                            </p>
                            <span class="text-leader2" data-role="hint" data-hint-text="{{ item.title }}">
                                <a href="{{ item.get_absolute_url }}">{{ item.title | truncatewords_html:7 }}</a>
                            </span>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <!-- LES PLUS LUS -->
    <div class="cell-md-4 mt-8">
        <div class="row">
            <div data-role="panel"
                class="w-100 p-0 "
                data-title-caption="<span class='text-leader fg-darkRed text-upper'>Les plus lus</sapn>"
                data-title-icon="<span class='mif-open-book'></span>"
                >
                <ul class="step-list">
                    {% for item in more_view %}
                        {% if item.view > 0 %}
                            <li class="img-container">
                                <div class="row">
                                    <div class="cell-sm-4">
                                        {% for media in item.medias.all %}
                                            {% if forloop.first %}
                                                <img class="avatar" src="{{ MEDIA_URL }}{{ media.source.url }}" alt="{{ item.title }}" >
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                    <div class="cell-sm-8">
                                        <span class="secondary-text "
                                            data-role="hint"
                                            data-hint-text="{{ item.title }}">
                                            <a href="{{ item.get_absolute_url }}">
                                                {{ item.title | truncatewords:6 }}
                                            </a>
                                        </span><br>
                                        <span class="text-small fg-darkGray">
                                            {{ item.created | date }}
                                            <span class="mif-eye ml-5"> {{ item.view }}</span>
                                        </span>
                                    </div>                                
                                </div>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <!-- /LES PLUS LUS -->
</div>
<!-- /DERNIÈRE NOUVELLES -->

templates/inc/last_videos.html
{% load static %}
{% load humanize %}

<!-- VIDEO -->
<div class="row">
    <div class="cell-md-8">
        <hr class="mt-10 border bd-dark border-top border-size-2">
        <div class="row">
            <div class="cell-md-12">
                <div class="h3 text-upper text-bold muted p-0 m-0 border fg-red">Vidéos</div>
            </div>
        </div>
        <div class="row">
            {% for video in videos %}
                <div class="cell-lg-4">
                    <div class="card">
                        <div class="card-header">
                            <div class="avatar">
                                <span class="mif-play mif-3x fg-red"></span>
                            </div>
                            <div class="name">{{ video.title | truncatewords:6 }}</div>
                            <div class="date">{{ video.created | date }}</div>
                        </div>
                        <div class="card-content p-2">
                            <a href="{{ video.get_absolute_url }}" class="flex">
                                <span class="mif-play mif-3x bg-red fg-white px-2" id="play" 
                                    style="position: absolute; top:-5px; left: 40%; border-radius: 50%">
                                </span>
                                {% for item in video.medias.all %}
                                    <img src="{{ MEDIA_URL }}{{ item.source.url }}" style="width: 100%">
                                {% endfor %}
                            </a>
                        </div>
                    </div>    
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="cell-md-4">
            <div class="row">
                <div class="cell-12 img-container p-10 my-10 figure text-center">
                    <a href="https://www.smartdevci.com" class="img-container text-center">
                        <img src="{% static '/img/logo-marron.png' %} " alt="pub" class="image w-50">
                    </a>
                    <div class="caption text-leader fg-red">Parténaire offciel</div>
                </div>
            </div>
    </div>
</div>
<!-- /VIDEO -->

templates/inc/navbar.html
{% load static %}

{% url 'news:home' as home_url %}
{% url 'news:actualites' as actu_url %}
<!-- {% url 'article' as article_url %} -->
{% url 'news:videos-list' as video_url %}
{% url 'news:events' as event_url %}



<div data-role="appbar" data-expand-point="md" class="bg-darkRed fg-white clear">
    <div class="">
        <a class="brand no-hover bg-white" >
            <img src="{% static 'img/logo.png' %} " alt="Logo" width="50">
        </a>
    </div>
    <ul class="app-bar-menu text-upper">
        <li class="{% if request.path == home_url %}bg-white fg-darkRed {% endif %}">
            <a href="{% url 'news:home' %}">Accueil</a>
        </li>
        <li class="{% if request.path == actu_url %}bg-white fg-darkRed {% endif %}">
            <a href="{% url 'news:actualites' %}">Actuaités</a>
        </li>
        <li class="{% if request.path == video_url %}bg-white fg-darkRed {% endif %}">
            <a href="{% url 'news:videos-list' %}">Vidéos</a>
        </li>
        <!-- <li>
            <a href="#">Oeuvres d'Arts</a>
        </li> -->
        <li class="{% if request.path == event_url %}bg-white fg-darkRed {% endif %}">
            <a href="{% url 'news:events' %}">Evénements</a>
        </li>    </ul>
</div>

templates/inc/news_top.html
{% load static %}
{% load humanize %}

<div class="bg-white p-5">
    <div class="row">
        <div class="cell-md-12  cell-lg-6">
            <div class="row">
                <div class="cell-lg-8 d-flex flex-align-stretch">
                    <div class="card">
                        <div class="card-header m-0 p-0">
                            {% for media in last_article.medias.all %}
                                <a href="{{ last_article.get_absolute_url }}" style="text-decoration: none">
                                    {% if forloop.first %}
                                        <img src="{{ MEDIA_URL }}{{ media.source.url }}" alt="last_article.id" class="w-100">
                                    {% endif %}
                                </a>
                            {% endfor %}
                        </div>
                        <div class="card-content p-3">
                            <div class="text-leader">
                                <a href="{{ last_article.get_absolute_url }}" style="text-decoration: none">
                                    {{ last_article.title }}
                                </a>
                            </div>
                            <hr>
                            <div class="text-secondary text-just wrap">
                                {{ last_article.content | safe | truncatewords_html:50 }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="cell-lg-4">
                    {% for article in articles %}
                        <div class="row">
                            <div class="card">
                                <div class="card-header m-0 p-0">
                                    {% for media in article.medias.all %}
                                        <a href="{{ article.get_absolute_url }}" style="text-decoration: none">
                                            {% if forloop.first %}
                                                <img src="{{ MEDIA_URL }}{{ media.source.url }}" alt="article.id" class="w-100">
                                            {% endif %}
                                        </a>
                                    {% endfor %}
                                </div>
                                <div class="card-content">
                                    <a href="{{ article.get_absolute_url }}" style="text-decoration: none">
                                        <div class="text-center p-1 text-secondary">{{ article.title }}</div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="cell-md-12 cell-lg-6">
            <div class="card">
            <iframe
                class="text-center card-header"
                width="100%" 
                height="398" 
                data-logo-height="65"

                {% for url_link in last_video.medias.all %}
                    src="{{ url_link.url }}"
                {% endfor %}
                frameborder="1" 
                allow="accelerometer; 
                autoplay; 
                encrypted-media; 
                gyroscope; 
                picture-in-picture" 
                allowfullscreen
            >
            </iframe>
            </div>
        </div>
    </div>
{#    <div class="row">#}
{#        {% for small_article in small_articles %}#}
{#            <div class="cell-md-6 cell-lg-3 p-0">#}
{#                <div class="card image-header">#}
{#                    <div class="card-header w-100 fg-white" #}
{#                        {% if forloop.first %}#}
{#                            style="{% for media in small_article.medias.all %}background-image: url('{{ MEDIA_URL }}{{ media.source.url }}');{% endfor %}"#}
{#                        {% endif %}#}
{##}
{#                    >#}
{#                        <div class="badge inline bg-red fg-white">#}
{#                            {{ small_article.category.description }} ICI nous sommes#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="card-content p-2">#}
{#                        <p class="muted fg-gray my-1">#}
{#                            <span class=" mif-user"></span>#}
{#                            <strong class="fg-red mr-5">#}
{#                                <em> {{ small_article.author | default_if_none:"Ben Saïba" | capfirst }} </em>#}
{#                            </strong>#}
{#                            <em class="mif-alarm">#}
{#                                {{ small_article.created | date }}#}
{#                                {{ small_article.created | date:"H:i" }}#}
{#                            </em>#}
{#                            <hr>#}
{#                            <a href="{{ small_article.get_absolute_url }}" class="text-leader">{{ small_article.title }}</a>#}
{#                        </p>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        {% endfor %}#}
{#    </div>#}
</div>

<hr class="mt-20 border bd-dark border-top border-size-2">